layout_spectrum: 1
color:
  saturation: 0.217007
  brandStrength: 1
  lightness: 0.09624389
  brandColors:
    - '#14141E'
    - '#B5B2B4'
    - '#88919B'
    - '#D8D5D2'
    - '#656E78'
  rhythmicContrast: 0.09496926
typography_spectrum: 0.1146953
name: Joshua
